#
# Makefile for Hypervisor interface
#

obj-$(CONFIG_TEGRA_HV_PM_CTL)		+= tegra_hv_pm_ctl.o

obj-$(CONFIG_TEGRA_HV_MANAGER)		+= tegra_hv.o
obj-$(CONFIG_TEGRA_HV_SYSFS)		+= hvc_sysfs.o
obj-$(CONFIG_TEGRA_HV_IVC_CDEV)		+= ivc-cdev.o
obj-$(CONFIG_TEGRA_HV_MEMPOOL_CDEV)	+= userspace_ivc_mempool.o

